services:
  - type: web
    name: perf-gym
    region: frankfurt
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_VERSION
        value: "18"
      - key: NEXT_TELEMETRY_DISABLED
        value: "1"
    autoDeploy: true
    repo: https://github.com/Yousef0hanafy/PrefGym